### ISSUE TITLE
这次更新之后都是错误..

### ISSUE THREAD

**Issue by owen-gxz** [liuzirui1122/zhuoyao_radar#30]
```

> zhuoyao-radar@1.0.0 dev /home/owen/git/zy2
> cross-env NODE_ENV='development' node ./build/dev-server.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by vitechliu** [comment]
本地没有这种情况 请删除node_modules重试 务必使用cnpm安装全部源

**Comment by galleonsZcc** [comment]
这是端口被占用，你换个端口就好了
